version: '2.17.2'
services:
  httpd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /home/marthen/Documents/Kuliah/seleksi-irk/scheduler-frontend
